spring.datasource.url=jdbc:mysql://${mysql.railway.internal}:${3306}/${railway}
spring.datasource.username=${root}
spring.datasource.password=${AyAnaXziIzRGdfvHLmsgHsClGMZoWcuO}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=skillbarter_secret_key_2024
jwt.expiration=86400000